baseurl = "https://tiredofit.github.io"
title = "Dave Conroy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Dave Conroy"
  info = "Digital sovereignty proponent"
  description = "Personal website of Dave Conroy"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/tiredofit/"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "contact/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/daveconroy"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about"
[[menu.main]]
  name = "Work with me"
  weight = 4
  url = "work"
[[menu.main]]
  name = "Contact"
  weight = 5
  url = "contact"
